---
- name: Install and Configure Grafana
  hosts: prom
  become: yes
  tasks:
    - name: Install required utilities
      apt:
        name:
          - apt-transport-https
          - software-properties-common
          - wget
        state: present
        update_cache: yes

    - name: Download Grafana GPG key
      get_url:
        url: https://apt.grafana.com/gpg.key
        dest: /usr/share/keyrings/grafana.key
        mode: '0644'

    - name: Add Grafana stable repository
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main"
        state: present
        filename: grafana.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Grafana (Open Source version)
      apt:
        name: grafana
        state: present

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Grafana service
      systemd:
        name: grafana-server
        state: started
        enabled: yes

    - name: Verify Grafana service status
      systemd:
        name: grafana-server
        state: started