---
- name: Install and Configure Prometheus Node Exporter
  hosts: nginx
  become: yes
  tasks:
    - name: Download Node Exporter binary
      get_url:
        url: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz
        dest: /tmp/node_exporter-0.18.1.linux-amd64.tar.gz

    - name: Extract Node Exporter binary
      unarchive:
        src: /tmp/node_exporter-0.18.1.linux-amd64.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: Move Node Exporter binary to /usr/local/bin
      copy:
        src: /tmp/node_exporter-0.18.1.linux-amd64/node_exporter
        dest: /usr/local/bin/node_exporter
        remote_src: yes
        owner: root
        group: root
        mode: '0755'

    - name: Create a system user for Node Exporter
      user:
        name: node_exporter
        shell: /bin/false
        system: yes
        create_home: no

    - name: Create Node Exporter systemd service file
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          User=node_exporter
          Group=node_exporter
          Type=simple
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=multi-user.target
        owner: root
        group: root
        mode: '0644'

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Node Exporter service
      systemd:
        name: node_exporter
        state: started
        enabled: yes

    - name: Ensure Node Exporter is running
      systemd:
        name: node_exporter
        state: started
